
file = open("textfile.txt")
textfile = file.read()
print(textfile)
print("------")
textfile2 = file.read()
print(textfile2)
print("------")
file.seek(10)
textfile2 = file.read()
print(textfile2)
print("------")
file.seek(0)
print("suljettu on") if file.closed else print("ei kyl oo suljettu")
textfile2 = file.readline()
print(textfile2)
print("------")
file.seek(0)
textfile2 = file.readlines()
print(textfile2)
print("------")
print("suljettu on") if file.closed else print("ei kyl oo suljettu")
file.close()
print("----with open--")

with open("textfile.txt") as file:
    print(file.read())
print("suljettu on") if file.closed else print("ei kyl oo")